Modified start-slave to check for existing slave process and to log to un-suffixed log files, after first archiving any older files with a suffix.

diff --git a/bin/sparcle b/bin/sparcle
--- a/bin/sparcle
+++ b/bin/sparcle
@@ -336,18 +336,21 @@ function deploy-app-to-cluster {
 ## ----------------------------------------------------------------------------
 
 function start-slave {
-    local ip=$(echo $(hostname -I)) || abort "querying hostname failed"
-    local port=$(fgrep ${ip} ${SHARED_DIR}/gpu-slaves.txt |
-                     cut -f2 -d" " | cut -f2 -d:) ||
-        abort "inferring port from ip address failed"
-    local log_ext="$(mktemp -u XXXXXX)" || abort "creating slave log extension failed"
-    local log_file="${LOG_DIR}/slave.${log_ext}"
-    local dummy_log_file="${LOG_DIR}/dummytf.${log_ext}"
+    ## Make sure there are no existing slave processes running.
+
+    pgrep -f -n "^java .+ -jar ${SHARED_DIR}/tf" > /dev/null &&
+        abort "slave already running"
+    pgrep -f -n "^/usr/bin/perl /shared/dummytf.pl ${DATA_DIR}" > /dev/null &&
+        abort "dummytf already running"
+
+    ## Create the log dir if necessary.
 
     if [ ! -d "${LOG_DIR}" ]; then
         sudo mkdir -p "${LOG_DIR}" || abort "creating log dir failed"
         sudo chmod a+rwx "${LOG_DIR}" || abort "setting log dir permissions failed"
     fi
+
+    ## Create the data dir if necessary.
 
     if [ ! -d "${DATA_DIR}" ]; then
         sudo mkdir -p "${DATA_DIR}/input" || abort "creating input dir failed"
@@ -356,11 +359,33 @@ function start-slave {
         sudo chmod -R a+rwx "${DATA_DIR}" || abort "setting data dir permissions failed"
     fi
 
+    ## Archive the old log files if present.
+
+    local log_ext="$(mktemp -u XXXXXX)" || abort "creating slave log extension failed"
+    local log_file="${LOG_DIR}/slave"
+    local dummy_log_file="${LOG_DIR}/dummytf"
+
+    if [[ -e "${log_file}" ]]; then
+        mv "${log_file}" "${log_file}.${log_ext}" ||
+            abort "archiving old slave log file ${log_file} failed"
+    fi
+
+    if [[ -e "${dummy_log_file}" ]]; then
+        mv "${dummy_log_file}" "${dummy_log_file}.${log_ext}" ||
+            abort "archiving old dummytf log file ${dummy_log_file} failed"
+    fi
+
+    ## Start the slave and dummy tensorflow processes.
+
+    local ip=$(echo $(hostname -I)) || abort "querying hostname failed"
+    local port=$(fgrep ${ip} ${SHARED_DIR}/gpu-slaves.txt |
+                     cut -f2 -d" " | cut -f2 -d:) ||
+        abort "inferring port from ip address failed"
+
     set -m
 
     nohup ${SHARED_DIR}/runtfserver.sh localhost ${port} > ${log_file} 2>&1 ||
         abort "starting slave on ip ${ip} port ${port} failed" &
-
     nohup ${SHARED_DIR}/dummytf.pl "${DATA_DIR}" > ${dummy_log_file} 2>&1 ||
         abort "starting dummytf on ip ${ip} failed" &
 }
