Made stop-slave and stop-master kill all instances, not just the most recent instance.

diff --git a/bin/sparcle b/bin/sparcle
--- a/bin/sparcle
+++ b/bin/sparcle
@@ -394,7 +394,7 @@ function start-slave {
 
     ## Make sure there are no existing slave processes running.
 
-    if (pgrep -f -n "^java .+ -jar ${SHARED_DIR}/tf" > /dev/null); then
+    if (pgrep -f "^java .+ -jar ${SHARED_DIR}/tf" > /dev/null); then
         status "slave already running"
     else
         create-dirs
@@ -417,7 +417,7 @@ function start-slave {
         status "started slave on ip ${ip} port ${port}"
     fi
 
-    if (pgrep -f -n "^/usr/bin/perl /shared/dummytf.pl ${DATA_DIR}" > /dev/null); then
+    if (pgrep -f "^/usr/bin/perl /shared/dummytf.pl ${DATA_DIR}" > /dev/null); then
         status "dummytf already running"
     else
         create-dirs
@@ -454,8 +454,8 @@ function start-cluster-slaves { cluster-op "" start-remote-slave $@; }
 function stop-slave {
     local slave_pattern="^java .+ -jar ${SHARED_DIR}/tf"
 
-    if (pgrep -f -n "${slave_pattern}" > /dev/null); then
-        pkill -f -n "${slave_pattern}" || abort "killing slave failed"
+    if (pgrep -f "${slave_pattern}" > /dev/null); then
+        pkill -f "${slave_pattern}" || abort "killing slave failed"
         status "killed slave"
     else
         status "slave already stopped"
@@ -463,8 +463,8 @@ function stop-slave {
 
     local dummy_pattern="^/usr/bin/perl /shared/dummytf.pl ${DATA_DIR}"
 
-    if (pgrep -f -n "${dummy_pattern}" > /dev/null); then
-        pkill -f -n "${dummy_pattern}" || abort "killing slave failed"
+    if (pgrep -f "${dummy_pattern}" > /dev/null); then
+        pkill -f "${dummy_pattern}" || abort "killing slave failed"
         status "killed dummytf"
     else
         status "dummtf already stopped"
@@ -483,7 +483,7 @@ function start-master {
 
     local pattern="^java .+ org.openchai.tensorflow.DirectSubmitter"
 
-    if (pgrep -f -n "${pattern}" > /dev/null); then
+    if (pgrep -f "${pattern}" > /dev/null); then
         status "master already running"
         return
     fi
@@ -541,8 +541,8 @@ function start-cluster-masters { cluster-op start-remote-master "" $@; }
 function stop-master {
     local pattern="^java .+ org.openchai.tensorflow.DirectSubmitter"
 
-    if (pgrep -f -n "${pattern}" > /dev/null); then
-        pkill -f -n "${pattern}" || abort "killing master failed"
+    if (pgrep -f "${pattern}" > /dev/null); then
+        pkill -f "${pattern}" || abort "killing master failed"
         status "killed master"
     else
         status "master already stopped"
